# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit
language: en-US
reviews:
  profile: chill
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "src/**/*.py"
      instructions: "Review for Python best practices, type safety, and clean architecture. Check for hardcoded values that should be configurable."
    - path: "tests/**/*.py"
      instructions: "Verify tests are meaningful. Check edge cases and mocking quality."
    - path: "scripts/**"
      instructions: "Check for shell scripting best practices, macOS compatibility, and security (no secrets, proper quoting)."
    - path: "examples/**"
      instructions: "Ensure no hardcoded usernames, company names, or internal references. Everything should use placeholders."
chat:
  auto_reply: true
